name: Create Recovery ROM

on:
  workflow_dispatch:
    inputs:
      EMPTY:
        description: 'Empty'
        required: false
        default: ''

jobs:
  build:
    name: Auto Firmware Dumper
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check Out
      uses: actions/checkout@v3

    - name: Clear the environment
      uses: rokibhasansagar/slimhub_actions@main

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
       swap-size-gb: 12

    - name: Updating packages
      run: |
        sudo apt update
        sudo apt upgrade -y
        sudo apt install curl python3 -y

    - name: Setting up environment
      run: |
        cd /home
        sudo mkdir mode=777 recovery_rom
        cd recovery_rom

    - name: Downloading and extracting stock ROM
      run: |
        mkdir stock
        cd stock
        wget https://mor1.androidfilehost.com/dl/eNODIzeVavWO08qdxomftQ/1702795391/4279422670115727738/%5BHovatek%5D_Tecno_Camon_20_Pro_%28CK7n-H894ABC-T-GL-230111V246%29.zip
        unzip *.zip
        rm -rf *.zip

    - name: Downloading flasher source
      run: |
        cd /home/recovery_rom
        git clone https://github.com/YZBruh/transsion-mt6789-CK7n-recovery_stock_rom -b master
        mv transsion* flasher

    - name: Moving files
      run: |
        cd stock/*
        wget https://raw.githubusercontent.com/unix3dgforce/lpunpack/master/lpunpack.py
        python3 lpunpack.py super.img super
        rm -rf super.unsparse.img super.img
        rm -rf vendor_dlk*
        dir=$(pwd)
        cd super
        mv odm_dlkm_a.img $dir/odm_dlkm_a.img
        mv odm_dlkm_b.img $dir/odm_dlkm_b.img
        mv vendor_dlkm_a.img $dir/vendor_dlkm_a.img
        mv vendor_dlkm_b.img $dir/vendor_dlkm_b.img
        mv product_a.img $dir/product_a.img
        mv product_b.img $dir/product_b.img
        mv system_a.img $dir/system_a.img
        mv system_b.img $dir/system_b.img
        mv system_ext_a.img $dir/system_ext_a.img
        mv system_ext_b.img $dir/system_ext_b.img
        mv vendor_a.img $dir/vendor_a.img
        mv vendor_b.img $dir/vendor_b.img
        cd $dir
        unset dir
        source_dir=$(pwd)
        destination_dir="/home/recovery_rom/flasher/images"
        find "$source_dir" -type f -name "*.img" -exec mv {} "$destination_dir" \;
        unset source_dir
        unset destination_dir
        cd /home/recovery_rom
        sudo mkdir mode=777 /home/temp
        mv flasher /home/temp
        rm -rf *
        mv /home/temp/flasher /home/recovery_rom/flasher
        cd /home/recovery_rom/flasher/images
        rm -rf preloader.img preloader_ck7n_h894.img preloader_emmc.img preloader_ufs.img userdata.img empty

    - name: Compressing ROM
      run: |
        cd /home/recovery_rom/flasher
        rm -rf generate_zip.sh
        rm -rf lpunpack
        rm -rf images/vendor_dlkm.img
        rm -rf images/odm_dlkm.img
        rm -rf images/vendor_boot-debug.img
        rm -rf images/super_empty.img
        file_name="CK7n_recovery_flashable_rom_A13"
        zip -r "$file_name" *
        mv "$file_name".zip /home/recovery_rom
        cd /home/recovery_rom
        rm -rf flasher

    - name: Uploading ROM transfer.sh
      run: |
        curl --upload-file ./"$file_name".zip https://transfer.sh/"$file_name".zip
        echo "Upload finished!"
        echo "Succesfull!"
        unset file_name
